sudo:required
services:
    - docker

before_install:
    - docker build -t arun/reactproject -f Dockerfile.dev .

script:
    - docker run -e CI=true  arun/reactproject npm run test

language: generic 

